# Generated by Django 4.2.5 on 2023-09-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pu_date',
            new_name='pub_date',
        ),
    ]
