# Generated by Django 4.2.5 on 2023-09-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_pu_date_product_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(default='', max_length=122)),
                ('phone', models.CharField(default='', max_length=12)),
                ('desc', models.TextField(default='')),
            ],
        ),
    ]
